/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    /*
    * Simple REPL-like loop that prints user input and
    * exits when receiving "quit"
    * */
    var input: String
    var quitFlag: Boolean = false

    while (!quitFlag) {
        print("Gimme something boy: ")
        input = readln()
        when (input.lowercase()) {
            "quit" -> quitFlag = true
            else -> println("\tGot $input")
        }
    }
}
